framework:
    secret: '%env(APP_SECRET)%'
    php_errors:
        log: true
    cache:
        default_memcached_provider: 'memcached://%memcached.host%:%memcached.port%'
        prefix_seed: '%kernel.name%'
    ide: 'phpstorm'
    validation: { enable_annotations: true }
